### ISSUE TITLE
LTO doesn't work with rust nightlies after 2020-04-29

### ISSUE THREAD

**Issue by jschwe** [hermitcore/rusty-hermit#15]
As reported in #7 building the rusty-demo with LTO doesn't work with rust nightlies newer than 2020-04-29. If this doesn't resolve by itself we should investigate what changed and if this requires any changes on our end in order to reenable LTO.

The error that gets printed when linking is the following:
`error: failed to get bitcode from object file for LTO (Bitcode section not found in object file)`

As a temporary workaround LTO was disabled in the release profile in #14

**Comment by tlambertz** [comment]
This is likely related to [Don't force rustc to do codegen for LTO builds](https://github.com/rust-lang/cargo/pull/8192), which makes cargo more lto-aware to speed up builds. But I am not sure where the problem lies exactly.

**Comment by jschwe** [comment]
This was merged only 3 days ago, so it probably isn't that specific PR (I'm assuming rust nightlies are built from master). However there seem to be a lot of related PRs concerning LTO and changing how it works in the past weeks.

**Comment by stlankes** [comment]
The problem is solved. At least it works on my test system.

**Comment by jschwe** [comment]
It's still broken for me.
Tested on windows with `rustc 1.45.0-nightly (ad4bc3323 2020-06-01)` and commit c68ef8ed2e72a988d27a286c1cc23f52db1533d6.
Both rusty_demo and netbench fail to compile in release mode with lto enabled with the error: `error: failed to get bitcode from object file for LTO (Bitcode section not found in object file)`

**Comment by stlankes** [comment]
I fixed it, but we have still an issue by building application with LTO support. The linker encodes the wrong OS ABI. See also rust-lang/rust#73606

**Comment by jschwe** [comment]
Looking at the PR, this only works for thin LTO, right? Commit https://github.com/hermitcore/rusty-hermit/pull/44/commits/66325e69fa026b03b943db6b26f2560187effe7d suggests that using full lto `lto = true` would still broken, correct?

**Comment by stlankes** [comment]
Yes, but this is also a bug in the Linker Plugin. I am able to link and to run with `lto = true`,  but the optimization is too aggressive. I was able to see, that the linker assumes that global data is partly constant, which isn't the case. I have to look in the details...

**Comment by jounathaen** [comment]
The `-C linker-plugin-lto` (or somethin simmilar) has to be set. e.g. int the `.cargo/config`

**Comment by stlankes** [comment]
Hm, can you set `-C linker-plugin-lto` only for `x86_64-unknown-hermit` **and** `release`version?

**Comment by stlankes** [comment]
I close this issue. The readme describes, how LTO can be activated.
